services:
  db:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: playground
    volumes:
      - ./docker/mysql/entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
